### ISSUE TITLE
Quest: The Absent Minded Prospector 

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#44]
**Description:**

The Absent Minded Prospector event is not working as it is supposed to. 

**Current behaviour:**

* Whenever he get attacked by one of the golems before he get to the first platform he says "_Now where did I put that mysterious fossil? Ah, maybe up there._" No matter where he is.

* As the event continue he keeps using wrong quotes at wrong spots.

* If he gets kill the quest won't fail in your Quest log. It stays active.

**Expected behaviour:**

Video here: https://www.youtube.com/watch?v=qHJv1qrpMLc

**Comment by frytik** [comment]
If he gets kill the quest won't fail in your Quest log. It stays active. - Fixed

Whenever he get attacked by one of the golems before he get to the first platform he says "Now where did I put that mysterious fossil? Ah, maybe up there." No matter where he is. - It should say that, but fixed.

As the event continue he keeps using wrong quotes at wrong spots. - Checking.

**Comment by frytik** [comment]
Fixed. Re-Test please.

**Comment by Deathtremor** [comment]
**Re-tested! Nothing has been fixed. Still the same issues! The escort is still broken. + The quest won't get complated after the escort quest ends.**

**Comment by JunkyBulgaria** [comment]
@Deathtremor  it's not applied yet, we are updating the compiling tools.

**Comment by Deathtremor** [comment]
Re-tested after the update. 

It's better, but still broken in some ways. Need polishing.

* He is not suppossed to say upon every attack: _Something tells me this: (name of mob) wants the mysterious fossil too. Help._ It wasn't like this back then on retail. 

* After he enteres the tent - he should not be attacked by Gravelflint Bonesnapper until about 3 sec after he says: Oh my what's this? Help! - **Currently he wont say this at all - He is attacked right after he approach the tent.**

* Golems behind this rocks should be out sight so they won't attack him or the player when he walks along the rocks. 

* From this part of the escort the rest is broken. Check the video how it should be. It's the best way how to explain it. https://youtu.be/qHJv1qrpMLc?t=1m28s
